# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

# Minecraft / NeoForge
# check these on https://projects.neoforged.net/neoforged/neoforge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neoforge_version=21.1.240
neoforge_version_range=[21.1.240,)
loader_version_range=[4,)

# Mod Properties
mod_id=pocket_repose
mod_name=PocketRepose
mod_named=Pocket Repose
mod_license=MIT
mod_version=1.3.2
tag_lanzador=NeoForge
mod_authors=BennyBoops
mod_description=A mod created for explorers in need of a trustworthy home.
maven_group=net.bennyboops.modid
mod_group_id=net.bennyboops
archives_base_name=pocket-repose

#dependencies
jei_version=19.44.0.403