modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/BennyBoops/PocketRepose/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://modrinth.com/mod/pocket-repose"
logoFile = "assets/pocket-repose/icon.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "pocket-repose.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
